### ISSUE TITLE
419 Error (CSRF Verification Error)

### ISSUE THREAD

**Issue by theutz** [anakadote/statamic-recaptcha#12]
I've run into this problem a few times, and I don't think it's something that you need to address in the code, but I thought I'd share it here in case anyone else comes across it.

Sometimes when the Statamic verification action is called, it returns a 419 error. Of course, the default behavior of this addon is to assume "error === robot", so it makes it seem like the person failed the reCAPTCHA evaluation.

In reality, in this case, the CSRF shouldn't matter much for this route. So you can bypass this problem by adding the reCAPTCHA verification route to the exclusion list in the CSRF middleware, like so:

```php
namespace App/Http/Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array<int, string>
     */
    protected $except = [
        '/!/statamic-recaptcha/verify-recaptcha-v3-token' // ADD THIS LINE HERE!
    ];
}
```

Might be worth adding something about this in the README, but I'll leave that to you!

**Comment by anakadote** [comment]
Thanks, @theutz! I'll leave this open for now, and consider adding to the readme.
