### ISSUE TITLE
ValidationException::withMessages don't display

### ISSUE THREAD

**Issue by drpark** [anakadote/statamic-recaptcha#14]
Hi there,
maybe i'm wrong, but it seems that throw ValidationException::withMessages([config('recaptcha.recaptcha_v3.error_message')]); don't display in the form.
the validation exception is throwed because the form is not sent and i can see the code throw the exception, but the error message don't display.

However i display all errors in the form. 
`{{ if errors }}
                        <div class="bg-red-600 text-white p-3 roundedall2">
                            {{ errors }}
                                {{ value }}<br>
                            {{ /errors }}
                        </div>
                    {{ /if }}`

Sorry if i misunderstand something, i'm just arriving in statamic/laravel world.
thank you

**Comment by anakadote** [comment]
I'm going to close this since it's pretty old, but fwiw here's the relevant documentation on why `ValidationException` is thrown: https://statamic.dev/extending/events#formsubmitted
