### ISSUE TITLE
Complaints from users about message "BOT...

### ISSUE THREAD

**Issue by vladislavbogomolov** [anakadote/statamic-recaptcha#16]
After installation on Statamic v4, we have many complaints from our users about message.

I don't understand why when the page loads you check if it's a bot and not just submitting the form. If I add a "nocaptcha" class on all forms will it only work by form submit?

**Comment by anakadote** [comment]
@vladislavbogomolov as of the latest version [(1.0.14)](https://github.com/anakadote/statamic-recaptcha/releases/tag/1.0.14) you can now disable the reCAPTCHA v3 verification on page load behavior via the new associated config setting:

```php
'recaptcha_v3' => [
...
        // In addition to performing the captcha verification when a form is submitted,
        // Statamic reCAPTCHA for v3 also runs on page load, and if it is determined
        // that the user is likely a bot, all forms on the page will be removed.
        // You can disable that behavior here by setting the below value to `false`.
        'verify_on_page_load' => false,
...
```

See the updated config file [here](https://github.com/anakadote/statamic-recaptcha/blob/main/config/recaptcha.php)

You'll also need to republish the JavaScript assets:
`php artisan vendor:publish --tag=statamic-recaptcha --force`
