### ISSUE TITLE
I always get the message Sorry, but you look like a robot.

### ISSUE THREAD

**Issue by pauantunez** [anakadote/statamic-recaptcha#18]
I am having problems with the implementation of the addon, I have followed all the steps in the documentation and in my forms I constantly get the message Sorry, but you look like a robot. 

Reviewing the code, I see that the error comes because the recaptcha-v3.js file has a request that returns a 404, it is the axios.post request. 

function initRecaptcha() {
    grecaptcha.ready(function() {
      const verifyUrl = '/!/statamic-recaptcha/verify-recaptcha-v3-token'

      if (! window.recaptchaV3.verifyOnPageLoad) {
        attachRecaptchaToForms()

      // Verify on page load, and remove forms from the DOM if the verification failed.
      } else {
        grecaptcha.execute(window.recaptchaV3.siteKey, {action: 'pageload/' + window.recaptchaV3.action})
          .then(function(token) {

            axios.post(verifyUrl, {token: token, action: 'pageload/' + window.recaptchaV3.action})
              .then(function(response) {
                attachRecaptchaToForms()
              })
              .catch(function(error) {
                const forms = document.querySelectorAll('form:not(.nocaptcha)')
                let errorMessage

                // Remove forms from the DOM and replace with an error message.
                for (let i = 0; i < forms.length; ++i) {
                  errorMessage = document.createElement('div')
                  errorMessage.className = 'alert alert-danger p-2 rounded bg-red-500'
                  errorMessage.setAttribute('role', 'alert')
                  errorMessage.innerHTML = error.response.data.error || 'Sorry, but you look like a robot.'

                  forms[i].parentNode.replaceChild(errorMessage, forms[i])
                }
              })
          })
      }
    })
  }

**Comment by anakadote** [comment]
@pauantunez  can you include a screenshot of the request from your console log?

**Comment by pauantunez** [comment]
I just solved it was a routing cache. Thanks
