### ISSUE TITLE
V3 form replace error message is a fixed string

### ISSUE THREAD

**Issue by lukeagsmith** [anakadote/statamic-recaptcha#19]
When the form is replaced with the error message in V3, it is replaced with the message "Sorry, but you look like a robot."

That message should be the one set in the config. Changing it in the published vendor JS means it gets overwritten every time the site is deployed.

**Comment by anakadote** [comment]
@lukeagsmith that's correct; you should never make updates to any package files aside from the config files, this package included. Closing this, as it isn't an issue, but seemingly just a piece of sound advice.

**Comment by lukeagsmith** [comment]
But surely the message the JS displays should be the message set in the config, which his not happening?

If I'm mistaken that it doesn't use the config message, how should I set the message the JS displays?

**Comment by anakadote** [comment]
@lukeagsmith if you followed the instructions correctly, then yes, the error message displayed can be changed via the published config file.
