### ISSUE TITLE
reCAPTCHA API Limit Error Logging

### ISSUE THREAD

**Issue by theutz** [anakadote/statamic-recaptcha#21]
## Feature Request

Log error responses from Google to help with debugging failed assessments.

### Context

Since Google is moving their reCAPTCHA stuff on to Google Cloud Platform, the interfaces for figuring out your billing situation is kinda in flux.

Earlier this week, the various sites connected to my Google Workspace hit the API limits for the free tier. There was no indication of this from Google at all. No emails, no errors in their dashboards (either reCAPTCHA Console or Google Cloud Platform). Nothing. Our forms just started returning "Sorry, you're a robot."

To find out what was wrong, I had to edit this [this line](https://github.com/anakadote/statamic-recaptcha/blob/7c02186b2338eb51be8550d128712848be8bf874/src/Services/RecaptchaV3.php#L30) to view the response from Google while tailing the logs, and the response there informed me I had hit an API limit.

That being said, it might be nice for error responses to be sent to the Laravel logs for easier debugging.

**Comment by theutz** [comment]
If this sounds good to you, I can whip up a PR to do it.

**Comment by anakadote** [comment]
@theutz  sure, a PR would be appreciated, thank you.

**Comment by anakadote** [comment]
@theutz this update is complete with the latest release [1.0.16](https://github.com/anakadote/statamic-recaptcha/releases/tag/1.0.16)

**Comment by theutz** [comment]
Oh, brilliant! Thank you!
