### ISSUE TITLE
404 on production site using statamic-recaptcha

### ISSUE THREAD

**Issue by nezaboravi** [anakadote/statamic-recaptcha#3]
Hello, thank you for making this plugin!

I am using it on codingwisely.com

I have set it as per READ.me document, and testing on local enviroment(codingwisely.test) works properly.
However, i have it on production keep saying that i am most likely a bot.

More over i get this in my error console and i dont know why is that URL not found (404)
Advise is much appreciated :)

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1515172/215455784-72a86fb1-6bcf-4fe9-916a-f892fcc7fee2.png">

**Comment by anakadote** [comment]
Hi @nezaboravi, do you have your routes cached? You may need to clear them:

`php artisan route:clear`

**Comment by nezaboravi** [comment]
> 

That fixed it. thank you!
