### ISSUE TITLE
Custom namespacing

### ISSUE THREAD

**Issue by m7vm7v** [anakadote/statamic-recaptcha#4]
The `RecaptchaController` uses the `use App\Http\Controllers\Controller;` but many applications use custom namespaces.
It'd be great if that could be updated.

Thanks

**Comment by m7vm7v** [comment]
A workaround, for now, is adding this to your `AppServiceProvider`

```
        $loader = AliasLoader::getInstance();
        $loader->alias('App\Http\Controllers\Controller', '{YOUR_NAMESPACE}\Http\Controllers\Controller');
```

**Comment by anakadote** [comment]
That seems like a pretty good workaround, or you could always fork this repo.
