### ISSUE TITLE
For Statamic 4.1.2 recaptcha is not supporting

### ISSUE THREAD

**Issue by subramanya-idaksh** [anakadote/statamic-recaptcha#7]
I recently updated the Statamic version to 4.1.2 and PHP 8.2.4. Now Forms and Cookie notices are showing an error message(You look like a robot). I tried reinstalling the plugin and also creating a new recaptcha key, but no use. Please support for this issue

**Comment by subramanya-idaksh** [comment]
Please any update?

**Comment by anakadote** [comment]
Hi @subramanya-idaksh Statamic 4 support is now included.

**Comment by subramanya-idaksh** [comment]
@anakadote Thank you for your support
