### ISSUE TITLE
Missing blade directive

### ISSUE THREAD

**Issue by jhhazelaar** [anakadote/statamic-recaptcha#8]
We have a project using blade as an template engine and we are missing the blade directive.

Any idea to implement a blade directive?

**Comment by jhhazelaar** [comment]
Workaround using Statamic tags for blade: https://statamic.dev/blade#using-tags-with-blade

`{!! Statamic::tag('recaptcha') !!}`

**Comment by aknEvrnky** [comment]
You can do this:

```php
{!! Statamic::tag('recaptcha')->fetch() !!}
```
