### ISSUE TITLE
Verify recaptcha token returns 404

### ISSUE THREAD

**Issue by martinoak** [anakadote/statamic-recaptcha#9]
Hey there, when I implement your reCaptcha, I get auto-evaluated as a bot. When I go to Developer tab in my browser, I see that I get 404 on this URL:

https://MYPAGE/!/statamic-recaptcha/verify-recaptcha-v3-token

**Comment by anakadote** [comment]
Hi @martinoak this seems like an Axios.js configuration issue, as the string "MYPAGE" doesn't appear in the code for this addon at all. I'm guess that your website is already using Axios.js, or is using another addon that uses it, and the `baseURL` is being set to "https://MYPAGE". 

See https://axios-http.com/docs/req_config
